version: '3.7'

services:

    # ---- Proxy ----------------------------------------------------------------
  dsf-dic-fhir-proxy:
    image: nginx:1.21
    restart: on-failure
    secrets:
    - proxy_certificate_and_int_cas.pem
    - proxy_certificate_private_key.pem
    - proxy_trusted_client_cas.pem
    volumes:
    - type: bind
      source: ./proxy/nginx.conf
      target: /etc/nginx/nginx.conf
      read_only: true
    environment:
      TZ: Europe/Berlin
    depends_on:
      - dsf-dic-fhir-app

  dsf-dic-fhir-app:
    image: ghcr.io/highmed/fhir:0.5.2
    restart: on-failure
    volumes:
    - type: bind
      source: ./fhir/app/conf/bundle.xml
      target: /opt/fhir/conf/bundle.xml
    secrets:
    - db_liquibase.password
    - db_fhir_dic_1_user.password
    - db_fhir_dic_1_user_permanent_delete.password
    - app_client_trust_certificates.pem
    - app_dic_1_client_certificate.pem
    - app_dic_1_client_certificate_private_key.pem
    - app_client_certificate_private_key.pem.password
    environment:
      ORG_HIGHMED_DSF_FHIR_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PASSWORD_FILE: /run/secrets/db_fhir_dic_1_user.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE: /run/secrets/db_fhir_dic_1_user_permanent_delete.password
      ORG_HIGHMED_DSF_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_dic_1_client_certificate.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_dic_1_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_FHIR_DB_URL: jdbc:postgresql://dsf-dic-fhir-db/fhir
      ORG_HIGHMED_DSF_FHIR_DB_USER_GROUP: dic_1_fhir_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_USERNAME: dic_1_fhir_server_user
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_GROUP: dic_1_fhir_permanent_delete_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_USERNAME: dic_1_fhir_server_permanent_delete_user
      ORG_HIGHMED_DSF_FHIR_SERVER_BASE_URL: https://dsf-dic-fhir-proxy/fhir
      ORG_HIGHMED_DSF_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_DIC_1
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS: "e2b39f27f51553a9f51a4dbda11cf7ac36339778af0d38a51cc85538dfde8b04837acc1dc8ec0a401cbe7867dbc9e1ba82e950fea4ca304aa3909541ad49fd16,d2e7338c3e9fc96a081b1a8983a847028859a68e5e318cb79cd6d0b2e9508e91698c373bbcdf56f774d6a9997e4a83a28fb6046ec80f8551ae38de49fe03b202"
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS_PERMANENT_DELETE: "e2b39f27f51553a9f51a4dbda11cf7ac36339778af0d38a51cc85538dfde8b04837acc1dc8ec0a401cbe7867dbc9e1ba82e950fea4ca304aa3909541ad49fd16,d2e7338c3e9fc96a081b1a8983a847028859a68e5e318cb79cd6d0b2e9508e91698c373bbcdf56f774d6a9997e4a83a28fb6046ec80f8551ae38de49fe03b202"
      EXTRA_JVM_ARGS: ${CODEX_DSF_ZARS_FHIR_APP_JVM_ARGS}
      TZ: Europe/Berlin
      #CORS_ORIGINS: "http://dsf-zars-bpe-app"
      # ORGANIZATION_TYPE: "MeDIC"  - needs to be put into the fhir resource organisation
    depends_on:
    - dsf-dic-fhir-db

  dsf-dic-fhir-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: fhir
    volumes:
    - type: volume
      source: dsf-dic-fhir-db-data
      target: /var/lib/postgresql/data
    secrets:
    - db_liquibase.password

  dsf-dic-bpe-app:
    image: ghcr.io/highmed/bpe:0.5.2
    restart: on-failure
    volumes:
      - type: bind
        source: ../../assets/codex-process-feasibility-0.1.0-RC6.jar
        target: /opt/bpe/process/codex-process-feasibility-0.1.0-RC6.jar
        read_only: true
      - type: bind
        source: ./bpe/app/last_event
        target: /opt/bpe/last_event
      - type: bind
        source: ../../assets/hapi-fhir-client-5.1.0.jar
        target: /opt/bpe/plugin/hapi-fhir-client-5.1.0.jar
        read_only: true
    secrets:
    - db_liquibase.password
    - db_dic_1_bpe_user.password
    - db_dic_1_bpe_user_camunda.password
    - app_client_trust_certificates.pem
    - app_dic_1_client_certificate.pem
    - app_dic_1_client_certificate_private_key.pem
    - app_client_certificate_private_key.pem.password
    environment:
      ORG_HIGHMED_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/db_dic_1_bpe_user.password
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_dic_1_bpe_user_camunda.password
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_dic_1_client_certificate.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_dic_1_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_BPE_DB_URL: jdbc:postgresql://dsf-dic-bpe-db/bpe
      ORG_HIGHMED_DSF_BPE_DB_USER_GROUP: dic_1_bpe_users
      ORG_HIGHMED_DSF_BPE_DB_USER_USERNAME: dic_1_bpe_server_user
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_GROUP: dic_1_camunda_users
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_USERNAME: dic_1_camunda_server_user
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_DIC_1
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_BASE_URL: https://dsf-dic-fhir-proxy/fhir
      DE_NETZWERK_UNIVERSITAETSMEDIZIN_CODEX_PROCESSES_FEASIBILITY_FLARE_WEBSERVICE_BASEURL: http://node-flare:5000/
      DE_NETZWERK_UNIVERSITAETSMEDIZIN_CODEX_PROCESSES_FEASIBILITY_FLARE_WEBSERVICE_CONNECTTIMEOUT: 2000
      DE_NETZWERK_UNIVERSITAETSMEDIZIN_CODEX_PROCESSES_FEASIBILITY_EVALUATION_STRATEGY: ${CODEX_FEASIBILITY_DSF_CLIENT_PROCESS_EVALUATION_STRATEGY:"structured-query"}
      DE_NETZWERK_UNIVERSITAETSMEDIZIN_CODEX_PROCESSES_FEASIBILITY_EVALUATION_OBFUSCATE: ${CODEX_FEASIBILITY_DSF_CLIENT_PROCESS_EVALUATION_OBFUSCATE:"true"}
      EXTRA_JVM_ARGS: ${CODEX_DSF_ZARS_BPE_APP_JVM_ARGS}
      TZ: "Europe/Berlin"
    depends_on:
    - dsf-dic-fhir-proxy
    - dsf-dic-bpe-db

  dsf-dic-bpe-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    volumes:
    - type: volume
      source: dsf-dic-bpe-db-data
      target: /var/lib/postgresql/data
    secrets:
    - db_liquibase.password

secrets:
  proxy_certificate_and_int_cas.pem:
    file: ../../secrets/proxy_certificate_and_int_cas.pem
  proxy_certificate_private_key.pem:
    file: ../../secrets/proxy_certificate_private_key.pem
  proxy_trusted_client_cas.pem:
    file: ../../secrets/proxy_trusted_client_cas.pem

  app_client_trust_certificates.pem:
    file: ../../secrets/app_client_trust_certificates.pem
  app_client_certificate_private_key.pem.password:
    file: ../../secrets/app_client_certificate_private_key.pem.password

  db_liquibase.password:
    file: ../../secrets/db_liquibase.password

  db_dic_1_bpe_user.password:
    file: ../../secrets/db_dic_1_bpe_user.password
  db_dic_1_bpe_user_camunda.password:
    file: ../../secrets/db_dic_1_bpe_user_camunda.password
  app_dic_1_client_certificate.pem:
    file: ../../secrets/app_dic_1_client_certificate.pem
  app_dic_1_client_certificate_private_key.pem:
    file: ../../secrets/app_dic_1_client_certificate_private_key.pem
  db_fhir_dic_1_user.password:
    file: ../../secrets/db_fhir_dic_1_user.password
  db_fhir_dic_1_user_permanent_delete.password:
    file: ../../secrets/db_fhir_dic_1_user_permanent_delete.password

volumes:
  dsf-dic-fhir-db-data:
    name: "dsf-dic-fhir-db-data"
  dsf-dic-bpe-db-data:
    name: "dsf-dic-bpe-db-data"
