services:
  zars-feasibility-gui:
    image: ghcr.io/num-codex/codex-feasibility-gui:0.0.2
    ports:
    - "443:443"
    volumes:
      - ../auth/cert.pem:/etc/nginx/conf.d/cert.pem
      - ../auth/key.pem:/etc/nginx/conf.d/key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mime.types:/etc/nginx/conf.d/mime.types
      - ./deploy-config.json:/usr/share/nginx/html/assets/config/config.deploy.json