version: '3.7'

services:

  # ---- Proxy ----------------------------------------------------------------
  dsf-dic-fhir-proxy:
    image: nginx:1.21
    restart: on-failure
    secrets:
    - proxy_certificate_and_int_cas.pem
    - proxy_certificate_private_key.pem
    - proxy_trusted_client_cas.pem
    volumes:
    - type: bind
      source: ./proxy/nginx.conf
      target: /etc/nginx/nginx.conf
      read_only: true
    environment:
      TZ: Europe/Berlin
    depends_on:
      - dsf-dic-fhir-app

  dsf-dic-fhir-app:
    image: ghcr.io/highmed/fhir:0.7.0
    restart: on-failure
    healthcheck:
      test: [ "CMD", "java", "-cp", "dsf_fhir.jar", "org.highmed.dsf.fhir.StatusClient" ]
      interval: 10s
      timeout: 15s
      retries: 5
    volumes:
    - type: bind
      source: ./fhir/app/conf/bundle.xml
      target: /opt/fhir/conf/bundle.xml
    secrets:
    - db_liquibase.password
    - db_fhir_dic_1_user.password
    - db_fhir_dic_1_user_permanent_delete.password
    - app_client_trust_certificates.pem
    - app_dic_1_client_certificate.pem
    - app_dic_1_client_certificate_private_key.pem
    - app_client_certificate_private_key.pem.password
    environment:
      ORG_HIGHMED_DSF_FHIR_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PASSWORD_FILE: /run/secrets/db_fhir_dic_1_user.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE: /run/secrets/db_fhir_dic_1_user_permanent_delete.password
      ORG_HIGHMED_DSF_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_dic_1_client_certificate.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_dic_1_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_FHIR_DB_URL: jdbc:postgresql://dsf-dic-fhir-db/fhir
      ORG_HIGHMED_DSF_FHIR_DB_USER_GROUP: dic_1_fhir_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_USERNAME: dic_1_fhir_server_user
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_GROUP: dic_1_fhir_permanent_delete_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_USERNAME: dic_1_fhir_server_permanent_delete_user
      ORG_HIGHMED_DSF_FHIR_SERVER_BASE_URL: https://dsf-dic-fhir-proxy/fhir
      ORG_HIGHMED_DSF_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: ${FEASIBILITY_DSF_CLIENT_PROCESS_ORGANIZATION_IDENTIFIER}
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS: ${FEASIBILITY_DSF_CLIENT_PROCESS_USER_THUMBPRINTS}
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS_PERMANENT_DELETE: ${FEASIBILITY_DSF_CLIENT_PROCESS_USER_THUMBPRINTS_PERMANENT_DELETE}
      EXTRA_JVM_ARGS: ${CODEX_DSF_ZARS_FHIR_APP_JVM_ARGS}
      TZ: Europe/Berlin
    depends_on:
    - dsf-dic-fhir-db

  dsf-dic-fhir-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: fhir
    volumes:
    - type: volume
      source: dsf-dic-fhir-db-data
      target: /var/lib/postgresql/data
    secrets:
    - db_liquibase.password

  dsf-dic-bpe-app:
    image: ghcr.io/highmed/bpe:0.7.0
    restart: on-failure
    healthcheck:
      test: [ "CMD", "java", "-cp", "dsf_bpe.jar", "org.highmed.dsf.bpe.StatusClient" ]
      interval: 10s
      timeout: 15s
      retries: 5
    volumes:
      - type: bind
        source: ../../assets/feasibility-dsf-process-0.3.0.jar
        target: /opt/bpe/process/feasibility-dsf-process-0.3.0.jar
        read_only: true
      - type: bind
        source: ./bpe/app/last_event
        target: /opt/bpe/last_event
      - type: bind
        source: ./bpe/cache
        target: /opt/bpe/cache
      - type: bind
        source: ../../assets/hapi-fhir-client-5.1.0.jar
        target: /opt/bpe/plugin/hapi-fhir-client-5.1.0.jar
        read_only: true
      # Use the following settings if you need to.
      # - type: bind
      #   source: <PATH_TO_TRUST_STORE>
      #   target: ${DSF_CLIENT_PROCESS_TRUST_STORE_PATH}
      #   read_only: true
      # - type: bind
      #   source: <PATH_TO_KEY_STORE>
      #   target: ${DSF_CLIENT_PROCESS_KEY_STORE_PATH}
      #   read_only: true
    secrets:
    - db_liquibase.password
    - db_dic_1_bpe_user.password
    - db_dic_1_bpe_user_camunda.password
    - app_client_trust_certificates.pem
    - app_dic_1_client_certificate.pem
    - app_dic_1_client_certificate_private_key.pem
    - app_client_certificate_private_key.pem.password
    environment:
      ORG_HIGHMED_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/db_dic_1_bpe_user.password
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_dic_1_bpe_user_camunda.password
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_dic_1_client_certificate.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_dic_1_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_BPE_DB_URL: jdbc:postgresql://dsf-dic-bpe-db/bpe
      ORG_HIGHMED_DSF_BPE_DB_USER_GROUP: dic_1_bpe_users
      ORG_HIGHMED_DSF_BPE_DB_USER_USERNAME: dic_1_bpe_server_user
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_GROUP: dic_1_camunda_users
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_USERNAME: dic_1_camunda_server_user
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: ${FEASIBILITY_DSF_CLIENT_PROCESS_ORGANIZATION_IDENTIFIER}
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_BASE_URL: https://dsf-dic-fhir-proxy/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_FLARE_WEBSERVICE_BASE_URL: ${FEASIBILITY_DSF_CLIENT_PROCESS_FLARE_WEBSERVICE_BASE_URL}
      DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_FLARE_WEBSERVICE_CONNECT_TIMEOUT: 2000
      DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_EVALUATION_STRATEGY: ${FEASIBILITY_DSF_CLIENT_PROCESS_EVALUATION_STRATEGY}
      DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_EVALUATION_OBFUSCATE: ${FEASIBILITY_DSF_CLIENT_PROCESS_EVALUATION_OBFUSCATE}
      # Use the following settings if you need to.
      # For more information see: https://github.com/medizininformatik-initiative/feasibility-dsf-process/tree/develop/feasibility-dsf-process#configuration
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_PROXY_HOST: ${FEASIBILITY_DSF_CLIENT_PROCESS_FORWARD_PROXY_HOST}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_PROXY_PORT: ${FEASIBILITY_DSF_CLIENT_PROCESS_FORWARD_PROXY_PORT}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_PROXY_USERNAME: ${FEASIBILITY_DSF_CLIENT_PROCESS_FORWARD_PROXY_USERNAME}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_PROXY_PASSWORD: ${FEASIBILITY_DSF_CLIENT_PROCESS_FORWARD_PROXY_PASSWORD}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_AUTH_BEARER_TOKEN: ${FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_BEARER_AUTH_TOKEN}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_AUTH_BASIC_USERNAME: ${FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_BASIC_AUTH_USERNAME}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_AUTH_BASIC_PASSWORD: ${FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_BASIC_AUTH_PASSWORD}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_TIMEOUT_CONNECT: ${FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_CONNECTION_TIMEOUT}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_TIMEOUT_CONNECT_REQUEST: ${FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_CONNECTION_REQUEST_TIMEOUT}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_TIMEOUT_SOCKET: ${FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_NETWORK_OPS_TIMEOUT}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_TRUST_STORE_PATH: ${FEASIBILITY_DSF_CLIENT_PROCESS_TRUST_STORE_PATH}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_TRUST_STORE_PASSWORD: ${FEASIBILITY_DSF_CLIENT_PROCESS_TRUST_STORE_PASSWORD}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_KEY_STORE_PATH: ${FEASIBILITY_DSF_CLIENT_PROCESS_KEY_STORE_PATH}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_KEY_STORE_PASSWORD: ${FEASIBILITY_DSF_CLIENT_PROCESS_KEY_STORE_PASSWORD}
      # DE_MEDIZININFORMATIK_INITIATIVE_FEASIBILITY_DSF_PROCESS_CLIENT_STORE_BASE_URL: ${FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_BASE_URL}
      EXTRA_JVM_ARGS: ${CODEX_DSF_ZARS_BPE_APP_JVM_ARGS}
      TZ: "Europe/Berlin"
    depends_on:
    - dsf-dic-fhir-proxy
    - dsf-dic-bpe-db

  dsf-dic-bpe-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    volumes:
    - type: volume
      source: dsf-dic-bpe-db-data
      target: /var/lib/postgresql/data
    secrets:
    - db_liquibase.password

secrets:
  proxy_certificate_and_int_cas.pem:
    file: ../../secrets/proxy_certificate_and_int_cas.pem
  proxy_certificate_private_key.pem:
    file: ../../secrets/proxy_certificate_private_key.pem
  proxy_trusted_client_cas.pem:
    file: ../../secrets/proxy_trusted_client_cas.pem

  app_client_trust_certificates.pem:
    file: ../../secrets/app_client_trust_certificates.pem
  app_client_certificate_private_key.pem.password:
    file: ../../secrets/app_client_certificate_private_key.pem.password

  db_liquibase.password:
    file: ../../secrets/db_liquibase.password

  db_dic_1_bpe_user.password:
    file: ../../secrets/db_dic_1_bpe_user.password
  db_dic_1_bpe_user_camunda.password:
    file: ../../secrets/db_dic_1_bpe_user_camunda.password
  app_dic_1_client_certificate.pem:
    file: ../../secrets/app_dic_1_client_certificate.pem
  app_dic_1_client_certificate_private_key.pem:
    file: ../../secrets/app_dic_1_client_certificate_private_key.pem
  db_fhir_dic_1_user.password:
    file: ../../secrets/db_fhir_dic_1_user.password
  db_fhir_dic_1_user_permanent_delete.password:
    file: ../../secrets/db_fhir_dic_1_user_permanent_delete.password



volumes:
  dsf-dic-fhir-db-data:
    name: "dsf-dic-fhir-db-data"
  dsf-dic-bpe-db-data:
    name: "dsf-dic-bpe-db-data"
