version: "3.7"

services:
  db:
    container_name: codexkeycloakdb
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
    volumes:
      - "db:/var/lib/postgresql/data"

  keycloak:
    container_name: codexkeycloak
    image: jboss/keycloak:15.0.2
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${FEASIBILITY_KEYCLOAK_ADMIN_PW:-admin}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: /tmp/initial-realm.json
      KEYCLOAK_FRONTEND_URL: ${FEASIBILITY_KEYCLOAK_BASE_URL:-https://localhost/auth}
    volumes:
      - ${KEYCLOAKIMPORTFILE:-./init/initial-realm-prod.json}:/tmp/initial-realm.json
      - ../auth/cert.pem:/etc/x509/https/tls.crt
      - ../auth/key.pem:/etc/x509/https/tls.key
    depends_on:
      - db

volumes:
  db:
