version: '3.7'

services:

  # ---- Proxy ----------------------------------------------------------------
  dsf-zars-fhir-proxy:
    image: nginx:1.21
    restart: on-failure
    ports:
    - "127.0.0.1:443:443"
    secrets:
    - proxy_certificate_and_int_cas.pem
    - proxy_certificate_private_key.pem
    - proxy_trusted_client_cas.pem
    volumes:
    - type: bind
      source: ./proxy/conf.d
      target: /etc/nginx/conf.d
      read_only: true
    - type: bind
      source: ./proxy/nginx.conf
      target: /etc/nginx/nginx.conf
      read_only: true
    environment:
      TZ: Europe/Berlin

  dsf-zars-fhir-app:
    image: ghcr.io/highmed/fhir:0.5.2
    restart: on-failure
    volumes:
    - type: bind
      source: ./fhir/app/conf/bundle.xml
      target: /opt/fhir/init/bundle.xml
    secrets:
      - db_liquibase.password
      - db_fhir_zars_user.password
      - db_fhir_zars_user_permanent_delete.password
      - app_client_trust_certificates.pem
      - app_zars_client_certificate.pem
      - app_zars_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
    environment:
      ORG_HIGHMED_DSF_FHIR_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PASSWORD_FILE: /run/secrets/db_fhir_zars_user.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE: /run/secrets/db_fhir_zars_user_permanent_delete.password
      ORG_HIGHMED_DSF_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_zars_client_certificate.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_zars_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_FHIR_DB_URL: "jdbc:postgresql://dsf-zars-fhir-db/fhir"
      ORG_HIGHMED_DSF_FHIR_DB_USER_GROUP: zars_fhir_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_USERNAME: zars_fhir_server_user
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_GROUP: zars_fhir_permanent_delete_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_USERNAME: zars_fhir_server_permanent_delete_user
      ORG_HIGHMED_DSF_FHIR_SERVER_BASE_URL: "https://dsf-zars-fhir-proxy/fhir"
      ORG_HIGHMED_DSF_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_ZARS
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS: ${ZARS_USER_THUMBPRINTS}
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS_PERMANENT_DELETE: ${ZARS_USER_THUMBPRINTS_PERMANENT_DELETE}
      EXTRA_JVM_ARGS: ${CODEX_DSF_ZARS_FHIR_APP_JVM_ARGS}
      TZ: Europe/Berlin
      #CORS_ORIGINS: "http://zars-feasibility-gui-backend"
      # ORGANIZATION_TYPE: "MeDIC"  - needs to be put into the fhir resource organisation
    depends_on:
    - dsf-zars-fhir-db

  dsf-zars-fhir-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: fhir
    volumes:
    - type: volume
      source: dsf-zars-fhir-db-data
      target: /var/lib/postgresql/data
    secrets:
    - db_liquibase.password

  # ZARS BPE ------------------------------------------------------------------
  dsf-zars-bpe-app:
    image: ghcr.io/highmed/bpe:0.5.2
    restart: on-failure
    volumes:
      - type: bind
        source: ../../assets/codex-process-feasibility-0.1.0-RC6.jar
        target: /opt/bpe/process/codex-process-feasibility-0.1.0-RC6.jar
        read_only: true
      - type: bind
        source: ./bpe/app/last_event
        target: /opt/bpe/last_event
    secrets:
      - db_liquibase.password
      - db_zars_bpe_user.password
      - db_zars_bpe_user_camunda.password
      - app_client_trust_certificates.pem
      - app_zars_client_certificate.pem
      - app_zars_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
    environment:
      ORG_HIGHMED_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/dsf-zars-bpe-postgres_password
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_zars_bpe_user_camunda.password
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_zars_client_certificate.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_zars_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_BPE_DB_URL: jdbc:postgresql://dsf-zars-bpe-db/bpe
      ORG_HIGHMED_DSF_BPE_DB_USER_GROUP: zars_bpe_users
      ORG_HIGHMED_DSF_BPE_DB_USER_USERNAME: zars_bpe_server_user
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_GROUP: zars_camunda_users
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_USERNAME: zars_camunda_server_user
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_ZARS
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_BASE_URL: "https://dsf-zars-fhir-proxy/fhir"
      EXTRA_JVM_ARGS: ${CODEX_DSF_ZARS_BPE_APP_JVM_ARGS}
      TZ: "Europe/Berlin"
      # WEBSOCKET_URL: "wss://dsf-zars-fhir-proxy/fhir/ws"
    depends_on:
    - dsf-zars-bpe-db
    - dsf-zars-fhir-proxy

  dsf-zars-bpe-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    volumes:
    - type: volume
      source: dsf-zars-bpe-db-data
      target: /var/lib/postgresql/data
    secrets:
    - db_liquibase.password

secrets:
  proxy_certificate_and_int_cas.pem:
    file:../../secrets/proxy_certificate_and_int_cas.pem
  proxy_certificate_private_key.pem:
    file:../../secrets/proxy_certificate_private_key.pem
  proxy_trusted_client_cas.pem:
    file:../../secrets/proxy_trusted_client_cas.pem

  app_client_trust_certificates.pem:
    file:../../secrets/app_client_trust_certificates.pem
  app_client_certificate_private_key.pem.password:
    file:../../secrets/app_client_certificate_private_key.pem.password

  db_liquibase.password:
    file:../../secrets/db_liquibase.password

  db_zars_bpe_user.password:
    file: secrets/db_zars_bpe_user.password
  db_zars_bpe_user_camunda.password:
    file: secrets/db_zars_bpe_user_camunda.password
  app_zars_client_certificate.pem:
    file:../../secrets/app_zars_client_certificate.pem
  app_zars_client_certificate_private_key.pem:
    file:../../secrets/app_zars_client_certificate_private_key.pem
  db_fhir_zars_user.password:
    file:../../secrets/db_fhir_zars_user.password
  db_fhir_zars_user_permanent_delete.password:
    file:../../secrets/db_fhir_zars_user_permanent_delete.password

  db_dic_1_bpe_user.password:
    file: secrets/db_dic_1_bpe_user.password
  db_dic_1_bpe_user_camunda.password:
    file: secrets/db_dic_1_bpe_user_camunda.password
  app_dic_1_client_certificate.pem:
    file:../../secrets/app_dic_1_client_certificate.pem
  app_dic_1_client_certificate_private_key.pem:
    file:../../secrets/app_dic_1_client_certificate_private_key.pem
  db_fhir_dic_1_user.password:
    file:../../secrets/db_fhir_dic_1_user.password
  db_fhir_dic_1_user_permanent_delete.password:
    file:../../secrets/db_fhir_dic_1_user_permanent_delete.password

  db_dic_2_bpe_user.password:
    file: secrets/db_dic_2_bpe_user.password
  db_dic_2_bpe_user_camunda.password:
    file: secrets/db_dic_2_bpe_user_camunda.password
  app_dic_2_client_certificate.pem:
    file:../../secrets/app_dic_2_client_certificate.pem
  app_dic_2_client_certificate_private_key.pem:
    file:../../secrets/app_dic_2_client_certificate_private_key.pem
  db_fhir_dic_2_user.password:
    file:../../secrets/db_fhir_dic_2_user.password
  db_fhir_dic_2_user_permanent_delete.password:
    file:../../secrets/db_fhir_dic_2_user_permanent_delete.password

volumes:
  dsf-zars-fhir-db-data:
    name: "dsf-zars-fhir-db-data"
  dsf-zars-bpe-db-data:
    name: "dsf-zars-bpe-db-data"
